import * as THREE from "three";
import { mergeGeometries } from "three/examples/jsm/utils/BufferGeometryUtils.js";
import { CHUNK_HEIGHT, CHUNK_SIZE } from "../types";
import type {
	ChunkContent,
	Environment,
	EnvironmentBuildParams,
} from "../types";

// ── Neural Environment (infinite 3D routing network) ─────────────────────────
//
// An endless volumetric web of router nodes joined by curved nerve paths, meant
// to read like the synapses of a nervous system. Unlike the `network`
// environment (loose points), the nodes here are solid little blobs and the
// paths are *tubes*, so the structure has real volume. Bright data packets fire
// along the paths from router to router.
//
// The world is a true 3D volume: this environment sets `verticalRadius`, so the
// ChunkManager streams chunk layers above and below the player as well — fly up
// or down and fresh network keeps appearing, never emptiness. (The scene drops
// its ground plane while a vertical environment is live, see
// ChunkManager.hasGroundFloor.)
//
// Generation is fully deterministic per *global* grid cell, not per chunk: a
// node's existence, position and every connection depend only on integer cell
// coordinates, so neighbouring chunks independently agree on the shared nodes at
// their border and the network joins up seamlessly across chunk boundaries.

// ─────────────────────────────────────────────────────────────────────────────
// NEURAL_CONFIG — the single place to tune the look. Colours, density, path and
// packet behaviour all live here. Density additionally scales live with the
// level's `buildingDensity` / `traceComplexity` knobs (see buildChunk).
// ─────────────────────────────────────────────────────────────────────────────
const NEURAL_CONFIG = {
	// Palette (change colours here) --------------------------------------------
	nodeColor: 0xdfe6ff, // router blobs
	pathColor: 0x4a5cff, // nerve tubes
	packetColor: 0x00ff66, // data packets travelling the paths (green cubes)
	glowColor: 0x6f8bff, // soft halo behind each node

	// Density ------------------------------------------------------------------
	// Baseline probabilities give a good-looking network on their own; the level's
	// buildingDensity / traceComplexity are *added* on top (see buildChunk), so a
	// level whose density is 0 still yields a populated net, and raising it thickens.
	cellSize: 44, // spacing of the global node grid (world units)
	nodeBaseProbability: 0.4, // baseline chance a grid cell holds a node
	connectionBaseProbability: 0.34, // baseline chance two neighbours link
	maxOutgoingPerNode: 3, // cap on paths a node originates (bounds cost)
	maxConnectionDist: 95, // drop links longer than this (world units)

	// Router node look ---------------------------------------------------------
	nodeRadius: 3.2,
	nodeScaleJitter: 0.7, // ± random size variation per node

	// Nerve path look ----------------------------------------------------------
	tubeRadius: 0.55,
	tubeTubularSegments: 14,
	tubeRadialSegments: 5,
	pathOpacity: 0.5,
	curveSag: 0.22, // sideways bow of a path, as a fraction of its length

	// Glow halo ----------------------------------------------------------------
	glowSize: 24,
	glowOpacity: 0.5,

	// Data packets -------------------------------------------------------------
	packetSize: 3.2,
	packetOpacity: 0.95,
	packetSpeed: 0.4, // fraction of a path traversed per second
	packetMinGap: 0.5, // min idle seconds on a path between firings
	packetMaxGap: 4.0, // max idle seconds on a path between firings

	// Volume / streaming -------------------------------------------------------
	verticalRadius: 1, // chunk layers streamed up & down (∞ in Y)

	// Growth -------------------------------------------------------------------
	growDuration: 0.9, // seconds a freshly-streamed chunk takes to grow in
};

// Forward neighbour offsets (positive half-space of the Chebyshev-1 shell). Each
// undirected pair of adjacent cells is visited exactly once — from the "lower"
// cell — so a connection is generated by only one of the two cells that share
// it, keeping the network free of duplicated paths.
const NEIGHBOR_OFFSETS: ReadonlyArray<readonly [number, number, number]> = [
	[1, 0, 0],
	[0, 1, 0],
	[0, 0, 1],
	[1, 1, 0],
	[1, -1, 0],
	[1, 0, 1],
	[1, 0, -1],
	[0, 1, 1],
	[0, 1, -1],
];

// ── Deterministic hashing (pure functions of integer cell coords) ────────────

function hashCell(x: number, y: number, z: number, salt: number): number {
	let h =
		Math.imul(x | 0, 0x27d4eb2d) ^
		Math.imul(y | 0, 0x165667b1) ^
		Math.imul(z | 0, 0x1b873593) ^
		Math.imul(salt | 0, 0x85ebca77);
	h ^= h >>> 15;
	h = Math.imul(h, 0x2c1b3c6d);
	h ^= h >>> 12;
	h = Math.imul(h, 0x297a2d39);
	h ^= h >>> 15;
	return h >>> 0;
}

/** [0,1) from a uint hash. */
function unit(h: number): number {
	return h / 4294967296;
}

/**
 * Symmetric [0,1) value for a pair of cell hashes — order-independent, so both
 * endpoints agree on whether they are connected regardless of who evaluates it.
 */
function pairUnit(a: number, b: number, salt: number): number {
	const lo = Math.min(a, b);
	const hi = Math.max(a, b);
	let h =
		Math.imul(lo ^ 0x9e3779b9, 0x85ebca6b) ^
		Math.imul(hi, 0xc2b2ae35) ^
		Math.imul(salt | 0, 0x27d4eb2d);
	h ^= h >>> 13;
	h = Math.imul(h, 0x5bd1e995);
	h ^= h >>> 15;
	return unit(h >>> 0);
}

interface CellNode {
	present: boolean;
	hash: number;
	/** World-space centre of the node. */
	x: number;
	y: number;
	z: number;
	/** Per-node size multiplier. */
	scale: number;
}

/** Fully deterministic node for a global grid cell (world-space). */
function cellNode(gx: number, gy: number, gz: number, nodeProb: number): CellNode {
	const cell = NEURAL_CONFIG.cellSize;
	const hash = hashCell(gx, gy, gz, 1);
	const present = unit(hash) < nodeProb;
	const jx = (unit(hashCell(gx, gy, gz, 11)) - 0.5) * cell * 0.7;
	const jy = (unit(hashCell(gx, gy, gz, 23)) - 0.5) * cell * 0.7;
	const jz = (unit(hashCell(gx, gy, gz, 31)) - 0.5) * cell * 0.7;
	const scale = 1 + (unit(hashCell(gx, gy, gz, 41)) - 0.5) * NEURAL_CONFIG.nodeScaleJitter;
	return {
		present,
		hash,
		x: gx * cell + jx,
		y: gy * cell + jy,
		z: gz * cell + jz,
		scale,
	};
}

/** Which chunk index (along one axis) owns global cell `g`. */
function ownerChunk(g: number, axisChunkSize: number): number {
	return Math.round((g * NEURAL_CONFIG.cellSize) / axisChunkSize);
}

// ── Shared glow sprite texture (soft radial dot) ─────────────────────────────

function makeGlowTexture(): THREE.Texture {
	const size = 64;
	const canvas = document.createElement("canvas");
	canvas.width = canvas.height = size;
	const ctx = canvas.getContext("2d")!;
	const g = ctx.createRadialGradient(size / 2, size / 2, 0, size / 2, size / 2, size / 2);
	g.addColorStop(0, "rgba(255,255,255,1)");
	g.addColorStop(0.25, "rgba(255,255,255,0.55)");
	g.addColorStop(1, "rgba(255,255,255,0)");
	ctx.fillStyle = g;
	ctx.fillRect(0, 0, size, size);
	const tex = new THREE.Texture(canvas);
	tex.needsUpdate = true;
	return tex;
}

// Reused scratch objects (avoid per-frame allocation).
const _mat4 = new THREE.Matrix4();
const _quat = new THREE.Quaternion();
const _scl = new THREE.Vector3();
const _pt = new THREE.Vector3();

interface PacketState {
	curve: THREE.CatmullRomCurve3;
	t: number;
	firing: boolean;
	gap: number;
}

class NeuralChunk implements ChunkContent {
	readonly group = new THREE.Group();
	readonly stationSlot: THREE.Vector3 | null;

	private readonly spawnTime: number;
	private lastElapsed = 0;
	private grown = false;

	// Router nodes (instanced blobs) + their glow halos.
	private readonly nodeMesh: THREE.InstancedMesh | null;
	private readonly nodeLocalPos: THREE.Vector3[] = [];
	private readonly nodeScale: number[] = [];
	private readonly nodeMat: THREE.MeshBasicMaterial;
	private readonly glowGeo: THREE.BufferGeometry | null;
	private readonly glowMat: THREE.PointsMaterial;

	// Nerve paths (one merged tube mesh) + the packets travelling them.
	private readonly tubeMat: THREE.MeshBasicMaterial;
	private readonly tubeMesh: THREE.Mesh | null;
	private readonly packets: PacketState[] = [];
	private readonly packetBoxGeo: THREE.BoxGeometry;
	private readonly packetMat: THREE.MeshStandardMaterial;
	private readonly packetMesh: THREE.InstancedMesh | null;

	constructor(
		cx: number,
		cy: number,
		cz: number,
		params: EnvironmentBuildParams,
		spawnTime: number,
		nodeGeo: THREE.IcosahedronGeometry,
		glowTex: THREE.Texture,
	) {
		this.spawnTime = spawnTime;

		const originX = cx * CHUNK_SIZE;
		const originY = cy * CHUNK_HEIGHT;
		const originZ = cz * CHUNK_SIZE;
		this.group.position.set(originX, originY, originZ);

		// Density scaled live by the level knobs.
		const density = params.buildingDensity ?? 0.4;
		const complexity = params.traceComplexity ?? 0.6;
		const nodeProb = THREE.MathUtils.clamp(
			NEURAL_CONFIG.nodeBaseProbability * (1 + density),
			0.05,
			0.9,
		);
		const connProb = THREE.MathUtils.clamp(
			NEURAL_CONFIG.connectionBaseProbability * (1 + complexity),
			0.05,
			0.95,
		);

		// ── Collect the nodes this chunk owns ────────────────────────────
		const cell = NEURAL_CONFIG.cellSize;
		const gxLo = Math.floor(((cx - 0.5) * CHUNK_SIZE) / cell) - 1;
		const gxHi = Math.ceil(((cx + 0.5) * CHUNK_SIZE) / cell) + 1;
		const gyLo = Math.floor(((cy - 0.5) * CHUNK_HEIGHT) / cell) - 1;
		const gyHi = Math.ceil(((cy + 0.5) * CHUNK_HEIGHT) / cell) + 1;
		const gzLo = Math.floor(((cz - 0.5) * CHUNK_SIZE) / cell) - 1;
		const gzHi = Math.ceil(((cz + 0.5) * CHUNK_SIZE) / cell) + 1;

		const ownedCells: Array<{ gx: number; gy: number; gz: number; node: CellNode }> = [];
		for (let gx = gxLo; gx <= gxHi; gx++) {
			if (ownerChunk(gx, CHUNK_SIZE) !== cx) continue;
			for (let gy = gyLo; gy <= gyHi; gy++) {
				if (ownerChunk(gy, CHUNK_HEIGHT) !== cy) continue;
				for (let gz = gzLo; gz <= gzHi; gz++) {
					if (ownerChunk(gz, CHUNK_SIZE) !== cz) continue;
					const node = cellNode(gx, gy, gz, nodeProb);
					if (node.present) ownedCells.push({ gx, gy, gz, node });
				}
			}
		}

		this.nodeMat = new THREE.MeshBasicMaterial({ color: NEURAL_CONFIG.nodeColor });

		// ── Router node instances + glow halos ───────────────────────────
		if (ownedCells.length > 0) {
			this.nodeMesh = new THREE.InstancedMesh(nodeGeo, this.nodeMat, ownedCells.length);
			this.nodeMesh.frustumCulled = false;
			const glowPositions = new Float32Array(ownedCells.length * 3);
			for (let i = 0; i < ownedCells.length; i++) {
				const n = ownedCells[i].node;
				const local = new THREE.Vector3(n.x - originX, n.y - originY, n.z - originZ);
				this.nodeLocalPos.push(local);
				this.nodeScale.push(n.scale);
				// Start at scale ~0; growth animation scales them in.
				_mat4.compose(local, _quat.identity(), _scl.setScalar(0.001));
				this.nodeMesh.setMatrixAt(i, _mat4);
				glowPositions[i * 3] = local.x;
				glowPositions[i * 3 + 1] = local.y;
				glowPositions[i * 3 + 2] = local.z;
			}
			this.nodeMesh.instanceMatrix.needsUpdate = true;
			this.group.add(this.nodeMesh);

			this.glowGeo = new THREE.BufferGeometry();
			this.glowGeo.setAttribute("position", new THREE.BufferAttribute(glowPositions, 3));
			this.glowMat = new THREE.PointsMaterial({
				color: NEURAL_CONFIG.glowColor,
				map: glowTex,
				size: NEURAL_CONFIG.glowSize,
				sizeAttenuation: true,
				blending: THREE.AdditiveBlending,
				transparent: true,
				opacity: 0,
				depthWrite: false,
			});
			const glow = new THREE.Points(this.glowGeo, this.glowMat);
			glow.frustumCulled = false;
			this.group.add(glow);
		} else {
			this.nodeMesh = null;
			this.glowGeo = null;
			this.glowMat = new THREE.PointsMaterial();
		}

		// ── Nerve paths (curved tubes) + packet curves ───────────────────
		const tubeGeos: THREE.TubeGeometry[] = [];
		const cx2 = cx;
		const cy2 = cy;
		const cz2 = cz;
		for (const owner of ownedCells) {
			let built = 0;
			for (const [ox, oy, oz] of NEIGHBOR_OFFSETS) {
				if (built >= NEURAL_CONFIG.maxOutgoingPerNode) break;
				const nx = owner.gx + ox;
				const ny = owner.gy + oy;
				const nz = owner.gz + oz;
				const other = cellNode(nx, ny, nz, nodeProb);
				if (!other.present) continue;
				if (pairUnit(owner.node.hash, other.hash, 7) >= connProb) continue;

				const a = owner.node;
				const dx = other.x - a.x;
				const dy = other.y - a.y;
				const dz = other.z - a.z;
				const dist = Math.hypot(dx, dy, dz);
				if (dist > NEURAL_CONFIG.maxConnectionDist) continue;

				// Local-space endpoints (relative to this chunk's origin).
				const aLocal = new THREE.Vector3(a.x - cx2 * CHUNK_SIZE, a.y - cy2 * CHUNK_HEIGHT, a.z - cz2 * CHUNK_SIZE);
				const bLocal = new THREE.Vector3(other.x - cx2 * CHUNK_SIZE, other.y - cy2 * CHUNK_HEIGHT, other.z - cz2 * CHUNK_SIZE);

				// Bow the path sideways so it reads as an organic nerve, not a wire.
				const mid = aLocal.clone().lerp(bLocal, 0.5);
				const bow = dist * NEURAL_CONFIG.curveSag;
				mid.x += (pairUnit(a.hash, other.hash, 101) - 0.5) * bow * 2;
				mid.y += (pairUnit(a.hash, other.hash, 211) - 0.5) * bow * 2;
				mid.z += (pairUnit(a.hash, other.hash, 307) - 0.5) * bow * 2;

				const curve = new THREE.CatmullRomCurve3([aLocal, mid, bLocal]);
				tubeGeos.push(
					new THREE.TubeGeometry(
						curve,
						NEURAL_CONFIG.tubeTubularSegments,
						NEURAL_CONFIG.tubeRadius,
						NEURAL_CONFIG.tubeRadialSegments,
						false,
					),
				);
				this.packets.push({
					curve,
					t: 0,
					firing: false,
					gap: NEURAL_CONFIG.packetMinGap + Math.random() * NEURAL_CONFIG.packetMaxGap,
				});
				built++;
			}
		}

		this.tubeMat = new THREE.MeshBasicMaterial({
			color: NEURAL_CONFIG.pathColor,
			transparent: true,
			opacity: 0,
			blending: THREE.AdditiveBlending,
			depthWrite: false,
		});
		if (tubeGeos.length > 0) {
			const merged = mergeGeometries(tubeGeos, false);
			for (const g of tubeGeos) g.dispose();
			if (merged) {
				this.tubeMesh = new THREE.Mesh(merged, this.tubeMat);
				this.tubeMesh.frustumCulled = false;
				this.group.add(this.tubeMesh);
			} else {
				this.tubeMesh = null;
			}
		} else {
			this.tubeMesh = null;
		}

		// ── Data packets (instanced green cubes) ────────────────────────
		this.packetBoxGeo = new THREE.BoxGeometry(
			NEURAL_CONFIG.packetSize * 0.6,
			NEURAL_CONFIG.packetSize * 0.6,
			NEURAL_CONFIG.packetSize * 0.6,
		);
		this.packetMat = new THREE.MeshStandardMaterial({
			color: NEURAL_CONFIG.packetColor,
			emissive: NEURAL_CONFIG.packetColor,
			emissiveIntensity: 0.8,
			metalness: 0.3,
			roughness: 0.5,
		});
		if (this.packets.length > 0) {
			this.packetMesh = new THREE.InstancedMesh(
				this.packetBoxGeo,
				this.packetMat,
				this.packets.length,
			);
			this.packetMesh.frustumCulled = false;
			// Start all instances hidden (scale 0).
			_mat4.identity();
			_scl.setScalar(0);
			for (let i = 0; i < this.packets.length; i++) {
				_mat4.compose(_pt.set(0, 0, 0), _quat.identity(), _scl);
				this.packetMesh.setMatrixAt(i, _mat4);
			}
			this.packetMesh.instanceMatrix.needsUpdate = true;
			this.group.add(this.packetMesh);
		} else {
			this.packetMesh = null;
		}

		// The station layer follows the player (ChunkManager), so the slot sits at
		// this chunk's world-XZ centre on its own layer (originY) — the station
		// appears at the height the player is flying, not pinned to y = 0.
		this.stationSlot =
			params.stationWeight > 0
				? new THREE.Vector3(originX, originY, originZ)
				: null;
	}

	update(elapsed: number): void {
		const delta = this.lastElapsed === 0 ? 0.016 : elapsed - this.lastElapsed;
		this.lastElapsed = elapsed;
		if (delta <= 0) return;

		// ── Growth: scale nodes in, fade paths & glow up ─────────────────
		if (!this.grown) {
			const grow = Math.min((elapsed - this.spawnTime) / NEURAL_CONFIG.growDuration, 1);
			const eased = 1 - (1 - grow) ** 3;
			if (this.nodeMesh) {
				for (let i = 0; i < this.nodeLocalPos.length; i++) {
					_mat4.compose(
						this.nodeLocalPos[i],
						_quat.identity(),
						_scl.setScalar(Math.max(0.001, this.nodeScale[i] * eased)),
					);
					this.nodeMesh.setMatrixAt(i, _mat4);
				}
				this.nodeMesh.instanceMatrix.needsUpdate = true;
			}
			this.tubeMat.opacity = NEURAL_CONFIG.pathOpacity * eased;
			this.glowMat.opacity = NEURAL_CONFIG.glowOpacity * eased;
			if (grow >= 1) this.grown = true;
		}

		// ── Data packets firing router → router ──────────────────────────
		if (this.grown && this.packetMesh) {
			for (let i = 0; i < this.packets.length; i++) {
				const st = this.packets[i];
				if (st.firing) {
					st.t += NEURAL_CONFIG.packetSpeed * delta;
					if (st.t >= 1) {
						st.firing = false;
						st.gap =
							NEURAL_CONFIG.packetMinGap +
							Math.random() * (NEURAL_CONFIG.packetMaxGap - NEURAL_CONFIG.packetMinGap);
						// Hide: scale to 0.
						_scl.setScalar(0);
						_pt.set(0, 0, 0);
					} else {
						st.curve.getPoint(st.t, _pt);
						_scl.setScalar(1);
					}
				} else {
					st.gap -= delta;
					if (st.gap <= 0) {
						st.firing = true;
						st.t = 0;
						_pt.copy(st.curve.points[0]);
						_scl.setScalar(1);
					} else {
						_scl.setScalar(0);
						_pt.set(0, 0, 0);
					}
				}
				_mat4.compose(_pt, _quat.identity(), _scl);
				this.packetMesh.setMatrixAt(i, _mat4);
			}
			this.packetMesh.instanceMatrix.needsUpdate = true;
		}
	}

	dispose(): void {
		// Node geometry + glow texture are shared (owned by the environment) — do
		// not dispose them here; only this chunk's own buffers and materials.
		this.tubeMesh?.geometry.dispose();
		this.tubeMat.dispose();
		this.nodeMat.dispose();
		this.glowGeo?.dispose();
		this.glowMat.dispose();
		this.packetBoxGeo.dispose();
		this.packetMat.dispose();
		if (this.packetMesh) this.packetMesh.dispose();
		this.group.clear();
	}
}

export class NeuralEnvironment implements Environment {
	readonly verticalRadius = NEURAL_CONFIG.verticalRadius;

	private readonly nodeGeo = new THREE.IcosahedronGeometry(NEURAL_CONFIG.nodeRadius, 1);
	private readonly glowTex = makeGlowTexture();

	buildChunk(
		cx: number,
		cy: number,
		cz: number,
		params: EnvironmentBuildParams,
		spawnTime: number,
	): ChunkContent {
		return new NeuralChunk(cx, cy, cz, params, spawnTime, this.nodeGeo, this.glowTex);
	}

	updateNeonColor(_color: THREE.Color): void {
		// Uses its own palette from NEURAL_CONFIG, not the level neon colour.
	}

	updateBuildingOpacity(_opacity: number): void {
		// No buildings to fade.
	}

	terrainHeightAt(_x: number, _z: number, _terrainLevel: number): number | null {
		// Volumetric world — no ground collision (see ChunkManager.hasGroundFloor).
		return null;
	}

	dispose(): void {
		this.nodeGeo.dispose();
		this.glowTex.dispose();
	}
}
