import type { ExperienceManifest, ParameterDef } from "../types";
import { updatePlayer } from "./player";
import { dispose, setup, tick } from "./scene";
import { applySettings } from "./settings";

const parameters: ParameterDef[] = [
	// ── Movement ────────────────────────────────────
	{
		id: "moveSpeed",
		label: "Movement Speed",
		group: "Movement",
		min: 1,
		max: 30,
		default: 8,
		step: 0.5,
		unit: "m/s",
		icon: "Gauge",
	},

	// ── WFC ─────────────────────────────────────────
	{
		id: "gridSize",
		label: "Grid Size",
		group: "WFC",
		min: 8,
		max: 40,
		default: 20,
		step: 1,
		icon: "Grid3x3",
	},
	{
		id: "cellSize",
		label: "Cell Size",
		group: "WFC",
		min: 2,
		max: 8,
		default: 4,
		step: 0.5,
		unit: "m",
		icon: "Maximize2",
	},
	{
		id: "buildingDensity",
		label: "Building Density",
		group: "WFC",
		min: 0,
		max: 1,
		default: 0.3,
		step: 0.05,
		icon: "Building2",
	},
	{
		id: "traceComplexity",
		label: "Trace Complexity",
		group: "WFC",
		min: 0,
		max: 1,
		default: 0.6,
		step: 0.05,
		icon: "CircuitBoard",
	},
	{
		id: "regenerate",
		label: "Regenerate",
		group: "WFC",
		type: "boolean",
		min: 0,
		max: 1,
		default: false,
		step: 1,
		icon: "RefreshCw",
	},

	// ── Visual ──────────────────────────────────────
	{
		id: "neonColor",
		label: "Neon Color",
		group: "Visual",
		type: "color",
		min: 0,
		max: 1,
		default: "#00ff66",
		step: 1,
		icon: "Palette",
	},
	{
		id: "buildingOpacity",
		label: "Building Opacity",
		group: "Visual",
		min: 0.1,
		max: 1,
		default: 0.7,
		step: 0.05,
		icon: "Eye",
	},
	{
		id: "animateData",
		label: "Animate Data Panels",
		group: "Visual",
		type: "boolean",
		min: 0,
		max: 1,
		default: true,
		step: 1,
		icon: "Monitor",
	},
];

export const manifest: ExperienceManifest = {
	// ── Identity ──
	id: "circuit3",
	name: "Data Room",
	description:
		"Cyberpunk circuit-board cityscape generated by Wave Function Collapse",
	version: "1.0.0",
	author: "Conrad und Catharina",

	// ── I/O Contract ──
	parameters,
	interfaces: { orientation: true, speed: false },

	// ── Scene Defaults ──
	camera: { fov: 70, near: 0.1, far: 600 },
	scene: {
		background: "#0a0a1a",
		fogNear: 50,
		fogFar: 300,
		fogColor: "#0a0a1a",
		ambientIntensity: 0.2,
		sunIntensity: 0.3,
		sunColor: "#4444ff",
		sunPosition: { x: 0, y: 100, z: 0 },
	},
	spawn: { position: { x: 0, y: 3, z: 0 } },

	// ── Lifecycle ──
	setup,
	tick,
	applySettings,
	updatePlayer,
	dispose,
};
